export enum ComponentsOfApplication {
    Home = "Home",
    Cart = "Cart",
    Admin = "Admin",
    Login = "Login",
    Single = "Single",
    NavBar = "NavBar",
    Profile = "Profile",
    TripAdd = "TripAdd",
    TripList = "TripList",
    Register = "Register",
    TripsList = "TripsList",
    TripRating = "TripRating",
    BuyHistory = "BuyHistory",
    TripDetail = "TripDetail",
}
